### ISSUE TITLE
Label and Description Customization

### ISSUE THREAD

**Issue by RCGTDev** [openspending/openspendingjs#69]
Where can i customize the Bubblemap Labels and Title label? How to enter Metadata? in which format?

I have my CSV file, here https://github.com/RCGTDev/A-donde-Van-Mis-Impuestos/blob/gh-pages/csv/by-cofog1-then-cofog2.csv

How can I visualize the labels of cofog_level1_name and cofog_level2_name?

**Comment by danfowler** [comment]
Hello! Thanks for your excellent question. I'm currently [thinking very hard about this very topic](https://discuss.okfn.org/t/openspending-next-visualization-experiment/886), and it is a work in progress.  In an attempt to address your use case, I thought one way toward this would be to slightly alter your aggregated CSV to only include the code names.  Example:

    "01","01.1",232151758
    "01","01.2",402301000
    "01","01.3",1385618086
    ... 

And then separately pass a `labels` key in your visualization initialization code.  Example:

     var data = {
        currency: "GBP",
        aggregated_csv_url: "csv/by-cofog1-then-cofog2.csv",
        amount_col_name: "amount",
        labels: {
          "root": "Total",
          "01":	"Servicios públicos generales",
          "02":	"Defensa",
          "03":	"Orden público y seguridad",
          ...

![screen shot 2015-09-21 at 12 46 39](https://cloud.githubusercontent.com/assets/772616/9989158/d7fab356-605e-11e5-879b-911777c73de9.png)

What do you think about this solution?

**Comment by hectorh30** [comment]
Hi danfowler,

Thanks a lot for the feedback. That solution would work for us for the time being (I'm currently working on the project that raised the issue).

We couln't get it to work though. Is your work in progress already available on your repo? Maybe on a specific branch?

We're currently testing with the [built version of the master branch](https://github.com/openspending/openspendingjs/blob/master/build/0.5.0/openspending.js), but I can't seem to locate where the labels key is being processed.

As far as I could follow the code the label's `<div />` element for each bubble [is created](https://github.com/openspending/openspendingjs/blob/master/build/0.5.0/openspending.js#L20751) in `BubbleTree.Bubbles.Icon` `show` function, which uses the `node.shortLabel` property (set in [the `init` function](https://github.com/openspending/openspendingjs/blob/master/build/0.5.0/openspending.js#L20721), from the `node.label` property).

Since we're using a local CSV instead of the APIs Aggregator, each node is [built with the CSV value as name](https://github.com/openspending/openspendingjs/blob/master/build/0.5.0/openspending.js#L22296), and so as label.

Would you mind pointing me on the right direction towards getting this example to work as in the image on your reply?

**Comment by danfowler** [comment]
Hi @hectorh30 sorry for the delay.  I had to have a think and then many other things got in the way :disappointed:.  I have added the front-end labeling to 0.5.1 and pushed it to master.  Please let me know if this helps and is what you were looking for.

There is a demo here: http://labs.openspending.org/openspendingjs/demo/bubbletree/#/~/total

HTML here: https://github.com/openspending/openspendingjs/blob/master/demo/bubbletree/index.html

**Comment by hectorh30** [comment]
@danfowler, we ended up making the local changes we needed to get it working for a little demo we had two weeks ago. But I'll have a look at the new version and update accordingly as soon as I get green light to go on.
Thanks a lot, and keep up the good work :-)

**Comment by danfowler** [comment]
:+1: gracias. Keep me updated :)
